version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: vertdb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: adminvert1
      MYSQL_USER: vert
      MYSQL_PASSWORD: Contabilid@de16
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    image: php:7.4-apache
    container_name: php_container
    volumes:
      - C:/vert/admin/:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  db_data:
